eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/
  instance:
    prefer-ip-address: true
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    lease-renewal-interval-in-seconds: 3
server:
  port: 7073
spring:
  application:
    name: service-zuul

